version: '3.8'

services:
  dev:
    build:
      context: .
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  prod:
    build:
      context: .
      target: runner
    # volumes:
    #   - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
